Issue 125] 날짜 선택 시간 범위 수정 및 날짜 선택 기본값 설정
b-side-g1/Dive pull request #143
Opened 2020-08-22 08:15 UTC by yeokyeong

- 날짜 선택 현재시간 이전만 가능
- 선택되어있는 날짜 현재 시간으로 지정

2020-08-24 00:18 UTC, kys6879 requested changes
RangeError (index): Invalid value: Not in inclusive range 0..11: -1

에러가 뜨네요.. 
다른 브랜치에선 안뜨는거봐서 이 PR에서 오류난거같아요
디바이스 시간은 오전 0시 15분, 마감시간은 21시로 테스트했습니다

2020-08-27 17:21 UTC, 1500sheep commented
변동 가능한 시간은
그날의 시작 시간 ~ 현재시간으로 변경해야 됩니다. 

**예**
그 날 시작 시간이 새벽 2:00, 현재 시간이 새벽 2:20분 ->  2:00 ~ 2:20 분까지만 변경 가능.

2020-08-27 17:25 UTC, 1500sheep commented
conflict 나는건 제가 input_page_step1.dart 파일 건드렸는데 
파악하지 못한게 있었네요
저희 스텝 1에서 
화살표만 누르면 바뀌는건 줄 알았는데
날짜 텍스트 영역 전체에 제스처를 걸어둬서 날짜를 변경할 수 있는거로 바뀌었나요?

이 부분 확인되면 제가 conflict 잡을게요!

2020-08-28 08:19 UTC, yeokyeong commented
> conflict 나는건 제가 input_page_step1.dart 파일 건드렸는데
> 파악하지 못한게 있었네요
> 저희 스텝 1에서
> 화살표만 누르면 바뀌는건 줄 알았는데
> 날짜 텍스트 영역 전체에 제스처를 걸어둬서 날짜를 변경할 수 있는거로 바뀌었나요?
> 
> 이 부분 확인되면 제가 conflict 잡을게요!

2020-09-05 16:28 UTC, 1500sheep approved these changes

2020-09-05 16:28 UTC, merged