데일리 페이지 pr 적용
b-side-g1/Dive pull request #54
Opened 2020-07-13 17:30 UTC by 1500sheep

- 저번에 말했던 테이블 컬럼 변경했습니다 (tag, emotion)
- UI 마무리는 데일리 페이지 카드 리스트 완료되면 반영하겠습니다.

2020-07-14 00:10 UTC, kys6879 commented
작업 중 또는 리뷰요청 라벨 적용 부탁드립니다!!

2020-07-14 11:13 UTC, TerryJoo approved these changes

2020-07-14 11:43 UTC, kys6879 requested changes
코드리뷰 확인 부탁드립니다 ! 🦾

2020-07-14 11:43 UTC, kys6879 commented on pubspec.yaml
> +    - lib/src/image/bottombar/3.0x/
bottombar/2.0x 와 3.0x 가 pubspec 에셋목록엔 있는데 실제 디렉토리는없어 오류메시지가 나오네요! 
수정되야할 것 같습니다!

2020-07-14 11:43 UTC, kys6879 commented on lib/pages/daily_page.dart
>                onPressed: () {
Widget _topNav() 위젯이 xxhdpi 모바일에서 깨진채로 나옵니다!
A RenderFlex overflowed by 24 pixels on the right. 라고 출력됩니다
확인 부탁드려요!

2020-07-14 11:46 UTC, kys6879 commented on pubspec.yaml
> +    - lib/src/image/bottombar/3.0x/
2.0x 3.0x 관련해서는 일단 눈대중으로 최대한 디자인가이드하고 비슷한 사진으로 맞춰주세요!
저 기능은 좀 더 연구해봐야 할 것 같습니다 ㅠㅠ

2020-07-18 12:50 UTC, yeokyeong approved these changes

2020-07-19 08:51 UTC, 1500sheep commented on lib/pages/daily_page.dart
>                onPressed: () {
이미지는 우선 추가했는데 경로를 어떻게 맞춰야 하나요??

2020-07-19 08:56 UTC, merged